/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License Version
 1.1 (the "License"); you may not use this file except in compliance with
 the License. You may obtain a copy of the License at
 http://www.mozilla.org/MPL/MPL-1.1.html
 
 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.
 
 The Original Code is the "OGC Service Framework".
 
 The Initial Developer of the Original Code is the VAST team at the University of Alabama in Huntsville (UAH). <http://vast.uah.edu> Portions created by the Initial Developer are Copyright (C) 2007 the Initial Developer. All Rights Reserved. Please Contact Mike Botts <mike.botts@uah.edu> for more information.
 
 Contributor(s): 
    Alexandre Robin <robin@nsstc.uah.edu>
 
******************************* END LICENSE BLOCK ***************************/

package org.vast.ows.swe;

import java.util.Map;
import javax.xml.namespace.QName;
import org.w3c.dom.*;
import org.vast.xml.DOMHelper;
import org.vast.ows.AbstractResponseReader;
import org.vast.ows.OWSResponse;


/**
 * <p>
 * Base abstract class for SWE services XML response readers
 * </p>
 *
 * @author Alex Robin
 * @date Oct 30, 2005
 * * @param <ResponseType> Type of OWS response object generated by this reader
 */
public abstract class SWEResponseReader<ResponseType extends OWSResponse> extends AbstractResponseReader<ResponseType>
{	
	
	public SWEResponseReader()
	{	
	}
	
	    
    /**
     * Reads common attributes and elements from XML response
     * @param dom
     * @param responseElt
     * @param response
     */
    protected void readXMLExtensions(DOMHelper dom, Element responseElt, OWSResponse response)
	{
    	// read extensions
    	Map<QName, Object> extObjs = SWESUtils.readXMLExtensions(dom, responseElt);
    	response.getExtensions().putAll(extObjs);
	}
}